# Generated by Django 3.2.7 on 2022-03-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('descripton', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('cover_photo', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Main Photo')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
