# Generated by Django 3.2.7 on 2022-03-31 13:40

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='ee', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(default='kamc', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
