# Generated by Django 3.2.7 on 2022-03-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220331_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='photo1',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Main Photo'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
