# Generated by Django 3.2.7 on 2022-04-03 16:18

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220331_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/', verbose_name='Main Photo'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, default='348133-sekogash-imate-izbor.jpg', force_format='JPEG', keep_meta=True, quality=85, size=[300, 200], upload_to=''),
        ),
    ]
